In [ ]:
import pandas as pd

df = pd.DataFrame({
    'id':(5,4,8,10),
    'lenguaje':('Python','Java','C','Cobol')
})
df.index = ['Cero','Uno','Dos','Tres']

df.head()

      id lenguaje
Cero   5   Python
Uno    4     Java
Dos    8        C
Tres  10    Cobol

In [ ]:
# Acceso a la columna
df['lenguaje']

Cero    Python
Uno       Java
Dos          C
Tres     Cobol
Name: lenguaje, dtype: object

In [ ]:
# (LOC) Acceso a una fila por su índice
df.loc['Uno']

id             4
lenguaje    Java
Name: Uno, dtype: object

In [ ]:
# (ILOC) Acceso a una fila por su posición
df.iloc[0]

id               5
lenguaje    Python
Name: Cero, dtype: object

In [ ]:
# (ILOC) Acceso a un conjunto de filas por su posición con slicing
df.iloc[0:2]

      id lenguaje
Cero   5   Python
Uno    4     Java

In [ ]:
# (ILOC) Obtención de las dos últimas filas
df.iloc[-2:]

      id lenguaje
Dos    8        C
Tres  10    Cobol

In [ ]:
# (ILOC) Obtención con slicing de combinaciones de filas y columnas
df.iloc[-2:,0:] # Dos últimas filas; Todas las columnas

      id lenguaje
Dos    8        C
Tres  10    Cobol

In [ ]:
# Acceso a un conjunto de filas por su índice utilizando slicing
df.loc['Uno':'Tres']

      id lenguaje
Uno    4     Java
Dos    8        C
Tres  10    Cobol