## Limpieza de un DF

In [ ]:
import pandas as pd

In [ ]:
clientes = pd.DataFrame({
  'nombre': ['Ana', 'Luis', 'Luis', None],
  'edad': [25, None, None, 40],
  'ciudad': ['Madrid ', 'Barcelona', 'Barcelona', 'Sevilla']
})
#clientes.drop_duplicates(inplace=True)
clientes = clientes.drop_duplicates()
clientes['edad'] = clientes['edad'].fillna(clientes['edad'].mean())
clientes['ciudad'] = clientes['ciudad'].str.strip()
clientes

  nombre  edad     ciudad
0    Ana  25.0     Madrid
1   Luis  32.5  Barcelona
3   None  40.0    Sevilla

## Función merge

In [ ]:
clientes = pd.DataFrame({
'id_cliente': [1, 2, 3, 4],
'nombre': ['Ana', 'Luis', 'Marta', 'Ramón']
})
ventas = pd.DataFrame({
'id_cliente': [1, 2, 3, 5],
'venta': [100, 200, 300, 800]
})
resultado = pd.merge(clientes, ventas, on='id_cliente') # Por defecto, inner
#resultado = pd.merge(clientes, ventas, on='id_cliente', how='inner') # Debe existir en los dos df
#resultado = pd.merge(clientes, ventas, on='id_cliente', how='left') # Toma todos los del primer df
#resultado = pd.merge(clientes, ventas, on='id_cliente', how='right') # Toma todos los del segundo df
#resultado = pd.merge(clientes, ventas, on='id_cliente', how='outer') # Toma todos los de los dos df

resultado

   id_cliente nombre  venta
0           1    Ana    100
1           2   Luis    200
2           3  Marta    300

## Método join

In [ ]:
empleados = pd.DataFrame({
'nombre': ['Ana', 'Luis'],
'departamento': ['Ventas', 'Marketing']
}, index=[1, 2])

salarios = pd.DataFrame({
'salario': [3000, 4000]
}, index=[1, 2])

resultado = empleados.join(salarios)
resultado

  nombre departamento  salario
1    Ana       Ventas     3000
2   Luis    Marketing     4000

## Pivot table (dataframe)

In [ ]:
ventas = pd.DataFrame(
    {
      'region': ['Norte', 'Norte', 'Sur', 'Sur','Norte', 'Norte'],
      'producto': ('A', 'B', 'A', 'B', 'A', 'B'),
      'ventas': [100, 150, 200, 250, 5, 7]
    }
)
ventas

  region producto  ventas
0  Norte        A     100
1  Norte        B     150
2    Sur        A     200
3    Sur        B     250
4  Norte        A       5
5  Norte        B       7

## Método pivot_table (transformación)

In [ ]:
pivot = ventas.pivot_table(
  values='ventas',
  index='producto',
  columns='region',
  aggfunc='sum'
)
pivot

region    Norte  Sur
producto
A           105  200
B           157  250

## Método pivot

In [ ]:
ventas = pd.DataFrame({
  'region': ['Norte', 'Norte', 'Sur', 'Sur','Este', 'Este'],
  'producto': ('A', 'B', 'A', 'B', 'A', 'B'),
  'ventas': [100, 150, 200, 250, 5, 7]
})
ventas

  region producto  ventas
0  Norte        A     100
1  Norte        B     150
2    Sur        A     200
3    Sur        B     250
4   Este        A       5
5   Este        B       7

In [ ]:
pivot = ventas.pivot(
  index='region',
  columns='producto',
  values='ventas'
)
pivot

producto    A    B
region
Este        5    7
Norte     100  150
Sur       200  250