In [ ]:
import pandas as pd

URL='http://fpaniaguapython.github.io/datos/CCAA-ULTIMOS-DOCE-MESES-LAPTOP-H55DSDJ2.csv'

df = pd.read_csv(URL, sep=';', thousands=".") # OJO, indicamos que los . son separadores de miles
df.drop(0, inplace=True) # OJO, se pierde el índice 0
df.head()

,comunidad,may-25,jun-25,jul-25,ago-25,sep-25,oct-25,nov-25,dic-25,ene-26,feb-26,mar-26,abr-26
1,ANDALUCIA,9200,10504,10582,7248,9472,10560,10035,10497,7731,9201,11510,9707
2,ARAGON,1401,1594,1628,1135,1448,1726,1668,1816,1206,1537,1746,1531
3,ASTURIAS,918,1304,1512,1511,1429,1475,1533,1454,916,1047,1404,1072
4,CANARIAS,4176,6646,5889,3304,4522,5581,5749,4090,2713,2608,5223,3290
5,CANTABRIA,752,796,790,730,770,931,781,930,655,762,858,744

In [ ]:
df.set_index('comunidad', inplace=True)
df.head()

,may-25,jun-25,jul-25,ago-25,sep-25,oct-25,nov-25,dic-25,ene-26,feb-26,mar-26,abr-26
comunidad,,,,,,,,,,,,
ANDALUCIA,9200,10504,10582,7248,9472,10560,10035,10497,7731,9201,11510,9707
ARAGON,1401,1594,1628,1135,1448,1726,1668,1816,1206,1537,1746,1531
ASTURIAS,918,1304,1512,1511,1429,1475,1533,1454,916,1047,1404,1072
CANARIAS,4176,6646,5889,3304,4522,5581,5749,4090,2713,2608,5223,3290
CANTABRIA,752,796,790,730,770,931,781,930,655,762,858,744

In [ ]:
#df.loc['CANTABRIA':'CEUTA','nov-25':]
df.loc['CANTABRIA':'CEUTA'].iloc[:,-6:]

                    nov-25  dic-25  ene-26  feb-26  mar-26  abr-26
comunidad
CANTABRIA              781     930     655     762     858     744
CASTILLA Y LEON       2539    2761    1975    2123    2698    2341
CASTILLA-LA MANCHA    2522    2596    1874    2222    2708    2157
CATALUÑA             12771   12203    9435   11134   13770   11830
CEUTA                   93      81      68      74      89      76

In [ ]:
df.iloc[0:6,1::2]

                 jun-25  ago-25  oct-25  dic-25  feb-26  abr-26
comunidad
ANDALUCIA         10504    7248   10560   10497    9201    9707
ARAGON             1594    1135    1726    1816    1537    1531
ASTURIAS           1304    1511    1475    1454    1047    1072
CANARIAS           6646    3304    5581    4090    2608    3290
CANTABRIA           796     730     931     930     762     744
CASTILLA Y LEON    2397    1994    2584    2761    2123    2341

In [ ]:
mascara = df['jun-25']>5000
df[mascara]

,may-25,jun-25,jul-25,ago-25,sep-25,oct-25,nov-25,dic-25,ene-26,feb-26,mar-26,abr-26
comunidad,,,,,,,,,,,,
ANDALUCIA,9200,10504,10582,7248,9472,10560,10035,10497,7731,9201,11510,9707
CANARIAS,4176,6646,5889,3304,4522,5581,5749,4090,2713,2608,5223,3290
CATALUÑA,11947,12485,12995,8255,11551,13080,12771,12203,9435,11134,13770,11830
COMUNIDAD DE MADRID,52701,56668,38101,20554,32549,37325,37071,44973,31340,47567,61757,47924
COMUNIDAD VALENCIANA,16160,12090,9621,5985,7951,8463,7937,8870,6539,8454,14416,13406

In [ ]:
# Registros de comunidades que a lo largo del año han matriculado más de
# 250000 automóviles
#df['total']=df.iloc[:].sum(axis=1)
df['total']=df.sum(axis=1)
df.head()
mascara = df['total']>60000
df[mascara]

,may-25,jun-25,jul-25,ago-25,sep-25,oct-25,nov-25,dic-25,ene-26,feb-26,mar-26,abr-26,total
comunidad,,,,,,,,,,,,,
ANDALUCIA,9200,10504,10582,7248,9472,10560,10035,10497,7731,9201,11510,9707,116247
CATALUÑA,11947,12485,12995,8255,11551,13080,12771,12203,9435,11134,13770,11830,141456
COMUNIDAD DE MADRID,52701,56668,38101,20554,32549,37325,37071,44973,31340,47567,61757,47924,508530
COMUNIDAD VALENCIANA,16160,12090,9621,5985,7951,8463,7937,8870,6539,8454,14416,13406,119892

In [ ]:
# Seleccionar los registros(Comunidades) cuyo total esté entre 25000 y 50000
mascara = (df['total']>=25000) & (df['total']<=50000)
df[mascara]
#mascara = df['total'].between(25000,50000)
#df[mascara]

,may-25,jun-25,jul-25,ago-25,sep-25,oct-25,nov-25,dic-25,ene-26,feb-26,mar-26,abr-26,total
comunidad,,,,,,,,,,,,,
CASTILLA Y LEON,2153,2397,2465,1994,2348,2584,2539,2761,1975,2123,2698,2341,28378
CASTILLA-LA MANCHA,2075,2216,2677,2155,2254,3149,2522,2596,1874,2222,2708,2157,28605
GALICIA,2572,2786,2561,2171,2548,2949,2758,3095,2300,2812,3060,2747,32359
ISLAS BALEARES,2478,2746,2456,1454,1630,1928,2043,2048,1278,1693,3952,3845,27551
PAIS VASCO,2773,2932,2887,1788,2742,2708,2570,2728,2050,2213,2735,2354,30480

In [ ]:
# Datos de jun-25 de comunidades que han matriculado menos de 10000
mascara = df['total']<10000
df.loc[mascara, 'jun-25']

comunidad
CANTABRIA    796
CEUTA         83
LA RIOJA     334
MELILLA      116
NAVARRA      753
Name: jun-25, dtype: int64