In [ ]:
import pandas as pd

DATOS_ANCHOS = 'https://fpaniaguapython.github.io/datos/datos_ventas_ancho.csv'
DATOS_LARGO = 'https://fpaniaguapython.github.io/datos/datos_ventas_largo.csv'

df_ventas = pd.read_csv(DATOS_ANCHOS, sep=',', header=0)

df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   mes          12 non-null     object
 1   extremadura  12 non-null     int64
 2   galicia      12 non-null     int64
 3   madrid       12 non-null     int64
 4   melilla      12 non-null     int64
 5   navarra      12 non-null     int64
 6   pais_vasco   12 non-null     int64
 7   la_rioja     12 non-null     int64
 8   ceuta        12 non-null     int64
dtypes: int64(8), object(1)
memory usage: 996.0+ bytes

In [ ]:
df_ventas.head()

,mes,extremadura,galicia,madrid,melilla,navarra,pais_vasco,la_rioja,ceuta
0,enero,120,210,480,15,55,190,30,35
1,febrero,110,200,450,14,53,180,28,32
2,marzo,130,225,520,16,60,205,34,38
3,abril,145,240,550,18,65,215,38,42
4,mayo,155,250,580,20,70,225,40,45

In [ ]:
ventas_altas = df_ventas[df_ventas['galicia'] > 220]
ventas_altas

,mes,extremadura,galicia,madrid,melilla,navarra,pais_vasco,la_rioja,ceuta
2,marzo,130,225,520,16,60,205,34,38
3,abril,145,240,550,18,65,215,38,42
4,mayo,155,250,580,20,70,225,40,45
5,junio,140,235,560,19,68,215,38,43
6,julio,165,270,620,22,75,240,43,48
7,agosto,160,260,610,21,73,235,42,47
8,septiembre,170,285,650,24,80,255,45,50
9,octubre,180,295,680,25,85,265,48,52
10,noviembre,195,310,720,27,90,280,50,55
11,diciembre,210,330,760,30,95,300,55,60

In [ ]:
# Opción 1 -> Ordenamos el DF
# df_ventas.sort_values(by='galicia', ascending=True, inplace=True)
# Opción 2 -> Generamos una copia ordenada del DF
df_ventas_ordenadas = df_ventas.sort_values(by='galicia', ascending=True, inplace=False)
df_ventas_ordenadas.head()

,mes,extremadura,galicia,madrid,melilla,navarra,pais_vasco,la_rioja,ceuta
1,febrero,110,200,450,14,53,180,28,32
0,enero,120,210,480,15,55,190,30,35
2,marzo,130,225,520,16,60,205,34,38
5,junio,140,235,560,19,68,215,38,43
3,abril,145,240,550,18,65,215,38,42

In [ ]:
df_ventas.isnull()

,mes,extremadura,galicia,madrid,melilla,navarra,pais_vasco,la_rioja,ceuta
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False

In [ ]:
df_ventas.columns = df_ventas.columns.str.capitalize()
df_ventas.columns

Index(['Mes', 'Extremadura', 'Galicia', 'Madrid', 'Melilla', 'Navarra',
       'Pais_vasco', 'La_rioja', 'Ceuta'],
      dtype='object')

In [ ]:
df_ventas['Mes'] = df_ventas['Mes'].str.capitalize()
df_ventas.head()

,Mes,Extremadura,Galicia,Madrid,Melilla,Navarra,Pais_vasco,La_rioja,Ceuta
0,Enero,120,210,480,15,55,190,30,35
1,Febrero,110,200,450,14,53,180,28,32
2,Marzo,130,225,520,16,60,205,34,38
3,Abril,145,240,550,18,65,215,38,42
4,Mayo,155,250,580,20,70,225,40,45

In [ ]:
df_ventas['GaliciaX10'] = df_ventas['Galicia']*10
df_ventas.head()

,Mes,Extremadura,Galicia,Madrid,Melilla,Navarra,Pais_vasco,La_rioja,Ceuta,GaliciaX10
0,Enero,120,210,480,15,55,190,30,35,2100
1,Febrero,110,200,450,14,53,180,28,32,2000
2,Marzo,130,225,520,16,60,205,34,38,2250
3,Abril,145,240,550,18,65,215,38,42,2400
4,Mayo,155,250,580,20,70,225,40,45,2500

In [ ]:
# Versión Javier - Asignando las condiciones a variables
#condicion_1 = df_ventas['Galicia']<240
#condicion_2 = df_ventas['Madrid']>300
# ventas_bajas = df_ventas[condicion_1 & condicion_2]

# Versión 'normal' - Asignando la condición en el filtro
ventas_bajas = df_ventas[(df_ventas['Galicia']<240) & (df_ventas['Madrid']>300)]
ventas_bajas

,Mes,Extremadura,Galicia,Madrid,Melilla,Navarra,Pais_vasco,La_rioja,Ceuta,GaliciaX10
0,Enero,120,210,480,15,55,190,30,35,2100
1,Febrero,110,200,450,14,53,180,28,32,2000
2,Marzo,130,225,520,16,60,205,34,38,2250
5,Junio,140,235,560,19,68,215,38,43,2350