In [389]:
import pandas as pd

URL = 'http://fpaniaguapython.github.io/datos/cntg-2026-05-26.csv'

dataframe = pd.read_csv(URL)

dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Marca temporal           20 non-null     object
 1   Nombre y apellidos       19 non-null     object
 2   Fecha de nacimiento      20 non-null     object
 3   Altura                   19 non-null     object
 4   Peso                     19 non-null     object
 5   Inglés                   19 non-null     float64
 6   Ciudad de residencia     19 non-null     object
 7   Ingresos brutos anuales  19 non-null     object
 8   Unnamed: 8               6 non-null      object
dtypes: float64(1), object(8)
memory usage: 1.5+ KB

In [390]:
dataframe.head(3)

,Marca temporal,Nombre y apellidos,Fecha de nacimiento,Altura,Peso,Inglés,Ciudad de residencia,Ingresos brutos anuales,Unnamed: 8
0,2026/05/26 6:08:01 p. m. EEST,Goya Ginger González,1991-12-15,166,60,5.0,Boqueixón,56000000,NaN
1,2026/05/26 6:08:23 p. m. EEST,Blanca García Gómez,2002-02-26,167,55,4.0,Santiago de Compostela,55000,NaN
2,2026/05/26 6:08:29 p. m. EEST,Raúl Hoyuelos Aranda,1969-08-13,180,75,3.0,Oleiros,100000,NaN

In [391]:
dataframe.tail(2)

,Marca temporal,Nombre y apellidos,Fecha de nacimiento,Altura,Peso,Inglés,Ciudad de residencia,Ingresos brutos anuales,Unnamed: 8
18,2026/05/26 6:10:01 p. m. EEST,Ana,1975-03-11,1.78,63,3.0,Santiago,40000,NaN
19,2026/05/26 6:10:11 p. m. EEST,Shaquira Pike Ramos,1979-09-24,"1, 68 metros",80 kg,3.0,Teo,20.000€,NaN

In [392]:
dataframe.sample(3)

,Marca temporal,Nombre y apellidos,Fecha de nacimiento,Altura,Peso,Inglés,Ciudad de residencia,Ingresos brutos anuales,Unnamed: 8
13,2026/05/26 6:09:33 p. m. EEST,Rosaura Perez Romasanta,1998-03-20,1.68,55,4.0,Vigo,25000,NaN
10,2026/05/26 6:09:15 p. m. EEST,Manuel Rodriguez,2000-05-26,168,60,5.0,vigo,10000,Opción 1
7,2026/05/26 6:09:13 p. m. EEST,Santi Rodrigo,1980-09-19,"1,7",70,3.0,Santiago de Compostela,23.000€,NaN

# Cambiar los nombres de las columnas

In [393]:
dataframe.columns = ('timestamp','nombre','fecha_nacimiento','altura','peso','ingles','ciudad','ingresos', 'unnamed')
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         20 non-null     object
 1   nombre            19 non-null     object
 2   fecha_nacimiento  20 non-null     object
 3   altura            19 non-null     object
 4   peso              19 non-null     object
 5   ingles            19 non-null     float64
 6   ciudad            19 non-null     object
 7   ingresos          19 non-null     object
 8   unnamed           6 non-null      object
dtypes: float64(1), object(8)
memory usage: 1.5+ KB

# Anonimizar los datos

In [394]:
dataframe['nombre']='Anónimo'
dataframe['nombre']

0     Anónimo
1     Anónimo
2     Anónimo
3     Anónimo
4     Anónimo
5     Anónimo
6     Anónimo
7     Anónimo
8     Anónimo
9     Anónimo
10    Anónimo
11    Anónimo
12    Anónimo
13    Anónimo
14    Anónimo
15    Anónimo
16    Anónimo
17    Anónimo
18    Anónimo
19    Anónimo
Name: nombre, dtype: object

# Reemplazar ' cm' por '' y ',' por '.'

In [395]:
dataframe['altura'] = dataframe['altura'].str.replace(' cm','').str.replace(',','.')
#dataframe['altura'] = dataframe['altura'].str.replace(' cm','')
#dataframe['altura'] = dataframe['altura'].str.replace(',','.')
dataframe.head(10)

,timestamp,nombre,fecha_nacimiento,altura,peso,ingles,ciudad,ingresos,unnamed
0,2026/05/26 6:08:01 p. m. EEST,Anónimo,1991-12-15,166,60,5.0,Boqueixón,56000000,NaN
1,2026/05/26 6:08:23 p. m. EEST,Anónimo,2002-02-26,167,55,4.0,Santiago de Compostela,55000,NaN
2,2026/05/26 6:08:29 p. m. EEST,Anónimo,1969-08-13,180,75,3.0,Oleiros,100000,NaN
3,2026/05/26 6:08:35 p. m. EEST,Anónimo,1991-05-10,NaN,70,NaN,Lugo,26500,Opción 1
4,2026/05/26 6:08:43 p. m. EEST,Anónimo,2002-05-18,250,83 kg,4.0,O Carballiño,50.000 euros,NaN
5,2026/05/26 6:09:05 p. m. EEST,Anónimo,0001-02-14,157,57,4.0,Santiago de Compostela,220000,Opción 1
6,2026/05/26 6:09:08 p. m. EEST,Anónimo,1980-03-06,1.70,80,3.0,Cuenca,50000,NaN
7,2026/05/26 6:09:13 p. m. EEST,Anónimo,1980-09-19,1.7,70,3.0,Santiago de Compostela,23.000€,NaN
8,2026/05/26 6:09:14 p. m. EEST,Anónimo,1998-02-28,180,79,3.0,NaN,NaN,NaN
9,2026/05/26 6:09:15 p. m. EEST,Anónimo,1888-05-22,1.99,120,3.0,Santiago,0,Opción 1

# Convertir a numérico la columna altura

In [396]:
dataframe['altura'] = pd.to_numeric(dataframe['altura'], errors='coerce')
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         20 non-null     object
 1   nombre            20 non-null     object
 2   fecha_nacimiento  20 non-null     object
 3   altura            18 non-null     float64
 4   peso              19 non-null     object
 5   ingles            19 non-null     float64
 6   ciudad            19 non-null     object
 7   ingresos          19 non-null     object
 8   unnamed           6 non-null      object
dtypes: float64(2), object(7)
memory usage: 1.5+ KB

Filtrar las alturas menores de 3 (serían metros y habría que convertirlos a centímetros)

In [397]:
dataframe.loc[dataframe['altura']<3, 'altura'] = dataframe.loc[dataframe['altura']<3]*100

/tmp/ipykernel_747/1136825840.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataframe['altura'].fillna(media, inplace=True)

,timestamp,nombre,fecha_nacimiento,altura,peso,ingles,ciudad,ingresos,unnamed
0,2026/05/26 6:08:01 p. m. EEST,Anónimo,1991-12-15,166.0,60,5.0,Boqueixón,56000000,NaN
1,2026/05/26 6:08:23 p. m. EEST,Anónimo,2002-02-26,167.0,55,4.0,Santiago de Compostela,55000,NaN
2,2026/05/26 6:08:29 p. m. EEST,Anónimo,1969-08-13,180.0,75,3.0,Oleiros,100000,NaN
3,2026/05/26 6:08:35 p. m. EEST,Anónimo,1991-05-10,179.0,70,NaN,Lugo,26500,Opción 1
4,2026/05/26 6:08:43 p. m. EEST,Anónimo,2002-05-18,250.0,83 kg,4.0,O Carballiño,50.000 euros,NaN
5,2026/05/26 6:09:05 p. m. EEST,Anónimo,0001-02-14,157.0,57,4.0,Santiago de Compostela,220000,Opción 1
6,2026/05/26 6:09:08 p. m. EEST,Anónimo,1980-03-06,170.0,80,3.0,Cuenca,50000,NaN
7,2026/05/26 6:09:13 p. m. EEST,Anónimo,1980-09-19,170.0,70,3.0,Santiago de Compostela,23.000€,NaN
8,2026/05/26 6:09:14 p. m. EEST,Anónimo,1998-02-28,180.0,79,3.0,NaN,NaN,NaN
9,2026/05/26 6:09:15 p. m. EEST,Anónimo,1888-05-22,199.0,120,3.0,Santiago,0,Opción 1

# Reemplazar los NaN por la media de la altura

In [ ]:
media = dataframe['altura'].mean()
dataframe['altura'].fillna(media, inplace=True)
dataframe.head(10)

# Convertir tipo de la altura

In [398]:
dataframe['altura'] = dataframe['altura'].astype('int64')
#dataframe.head(10)
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         20 non-null     object
 1   nombre            20 non-null     object
 2   fecha_nacimiento  20 non-null     object
 3   altura            20 non-null     int64
 4   peso              19 non-null     object
 5   ingles            19 non-null     float64
 6   ciudad            19 non-null     object
 7   ingresos          19 non-null     object
 8   unnamed           6 non-null      object
dtypes: float64(1), int64(1), object(7)
memory usage: 1.5+ KB