In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split # Troceador de datos de entrenamiento
import sklearn.linear_model as lm
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import joblib # Librería que permite almacenar los modelos serializados

from google.colab import drive # Para acceder a drive

drive.mount('/content/drive') # Para montar la unidad


URL = 'https://fpaniaguapython.github.io/datos/datos_regresion_lineal.csv'

df = pd.read_csv(URL)
df.head()

Mounted at /content/drive

,id,horas_sueño,peso,horas_ejercicio,genero,edad,profesion,colesterol
0,1,7,79,1,Hombre,25,Estudiante,175
1,2,8,72,2,Mujer,28,Ingeniera,168
2,3,6,85,1,Hombre,35,Profesor,190
3,4,7,68,3,Mujer,31,Diseñadora,162
4,5,5,92,0,Hombre,45,Contador,215

In [ ]:
df.drop(['profesion'], axis=1, inplace=True)

In [ ]:
df_completo = pd.get_dummies(df)

In [ ]:
X = df_completo.drop(['colesterol'], axis=1).drop(['id'], axis=1)

y = df_completo['colesterol']

In [ ]:
X

    horas_sueño  peso  horas_ejercicio  edad  genero_Hombre  genero_Mujer
0             7    79                1    25           True         False
1             8    72                2    28          False          True
2             6    85                1    35           True         False
3             7    68                3    31          False          True
4             5    92                0    45           True         False
..          ...   ...              ...   ...            ...           ...
95            7    68                2    30          False          True
96            8    75                3    34           True         False
97            6    82                1    40          False          True
98            7    79                2    31           True         False
99            8    61                4    26          False          True

[100 rows x 6 columns]

In [ ]:
y

0     175
1     168
2     190
3     162
4     215
     ...
95    168
96    172
97    190
98    177
99    154
Name: colesterol, Length: 100, dtype: int64

# Obtención de conjuntos de entrenamiento y test

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Entrenar el modelo

In [ ]:
modelo = lm.LinearRegression().fit(X_train, y_train)

# Almacenar el modelo

In [ ]:
joblib.dump(modelo, "/content/drive/MyDrive/modelo_regresion_datos_medicos.pkl")

['/content/drive/MyDrive/modelo_regresion_datos_medicos.pkl']

# Evaluación del modelo

In [ ]:
y_pred = modelo.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

# MAE: Significa que, en promedio, las predicciones del modelo se equivocan en 2.31 unidades respecto al valor real.
print("MAE:", mae) # MAE: error medio absoluto (cuanto menor, mejor).
print("RMSE:", rmse) # RMSE: error en las unidades del modelo.
print("R²:", r2) # R² 1 → predicción perfecta; 0 → igual que predecir la media; < 0 → peor que predecir la media.

MAE: 2.3115475108893593
RMSE: 3.0081042758640457
R²: 0.982051500137417

# Obtener predicción

In [ ]:
nuevo = pd.DataFrame({
    'horas_sueño': [7],
    'peso': [80],
    'horas_ejercicio': [2],
    'edad': [30],
    'genero_Hombre': [True],
    'genero_Mujer': [False]
})

prediccion = modelo.predict(nuevo)

print(prediccion)

[178.58442186]